### ISSUE TITLE
Right arm board error

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#369] opened 2017-01-25 13:46 UTC
:

### Description of the failure
356500	164454,014305	ERROR	 from BOARD 10.0.1.28 (rightArm-j8_11), src LOCAL, adr 0, time 543s 557m 85u: (code 0x04000002, par16 0x0000 par64 0x0000000000000000) -> DEBUG: tag02 + mais timeout

356603	164455,864600	ERROR	unable to complete calibration: joint 2 in 'hw_fault status' inside doneRaw() function

### Detailed conditions and logs of the failure

Upon starting yarprobotinterface I get the previously mentioned error messages.

**Comment by marcoaccame** [comment] 2017-01-30 20:14
Hi @fjandrad, can you please post the complete log?

**Comment by julijenv** [comment] 2017-02-02 12:05
Hi @fjandrad ,
any news?

**Comment by fjandrad** [comment] 2017-02-06 09:48
Sorry for the late response. It has not happened again you can close it.

**Comment by nunoguedelha** [comment] 2017-03-12 22:52
Closing this issue since it hasn't been reproduced for more than a month.

**Closed by nunoguedelha** 2017-03-12 22:52 UTC
Labels: iCubGenova04 (green)
